# Generated by Django 5.1.3 on 2024-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_alter_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='x',
            field=models.URLField(blank=True, null=True),
        ),
    ]
